export interface GeologicalFeature {
  name: string;
  type: string;
  description: string;
}

export interface AtmosphereComponent {
  name: string;
  percentage: number;
  color: string;
}

export interface MagneticFieldData {
  strength: string; // e.g. "31.25 µT"
  type: string; // dipole, weak, none
  tilt: number; // degrees from rotational axis
  description: string;
}

export interface PlanetSurfaceData {
  geologicalFeatures: GeologicalFeature[];
  atmosphere: AtmosphereComponent[];
  magneticField: MagneticFieldData;
}

export const planetSurfaceData: Record<string, PlanetSurfaceData> = {
  mercury: {
    geologicalFeatures: [
      { name: "Caloris Basin", type: "Impact Basin", description: "1,550 km diameter impact crater, one of the largest in the solar system" },
      { name: "Pantheon Fossae", type: "Tectonic", description: "Radial system of troughs centered within the Caloris Basin" },
      { name: "Discovery Rupes", type: "Scarp", description: "650 km long lobate scarp formed by planetary cooling and contraction" },
    ],
    atmosphere: [
      { name: "Sodium", percentage: 29, color: "hsl(40, 90%, 55%)" },
      { name: "Oxygen", percentage: 25, color: "hsl(200, 70%, 60%)" },
      { name: "Hydrogen", percentage: 22, color: "hsl(0, 0%, 75%)" },
      { name: "Helium", percentage: 15, color: "hsl(50, 80%, 70%)" },
      { name: "Potassium", percentage: 9, color: "hsl(280, 50%, 55%)" },
    ],
    magneticField: { strength: "0.3 µT", type: "dipole", tilt: 0, description: "Weak but present dipole field, ~1% of Earth's strength" },
  },
  venus: {
    geologicalFeatures: [
      { name: "Maxwell Montes", type: "Mountain", description: "Highest mountain on Venus, 11 km above mean surface level" },
      { name: "Maat Mons", type: "Volcano", description: "Largest volcano on Venus, 8 km high with evidence of recent lava flows" },
      { name: "Ishtar Terra", type: "Highland", description: "Continent-sized highland plateau near the north pole" },
    ],
    atmosphere: [
      { name: "CO₂", percentage: 96.5, color: "hsl(0, 0%, 55%)" },
      { name: "Nitrogen", percentage: 3.5, color: "hsl(210, 50%, 60%)" },
    ],
    magneticField: { strength: "~0 µT", type: "none", tilt: 0, description: "No intrinsic magnetic field; induced magnetosphere from solar wind interaction" },
  },
  earth: {
    geologicalFeatures: [
      { name: "Mid-Atlantic Ridge", type: "Tectonic", description: "Divergent plate boundary spanning 16,000 km along the Atlantic Ocean floor" },
      { name: "Mariana Trench", type: "Trench", description: "Deepest oceanic trench at 10,994 m, formed by subduction" },
      { name: "Olympus Mons (Hawaii)", type: "Hotspot Volcano", description: "Mauna Kea is Earth's tallest mountain from base to peak at 10,210 m" },
      { name: "Himalayas", type: "Mountain Range", description: "Youngest and highest mountain range, still rising at ~5mm/year" },
    ],
    atmosphere: [
      { name: "Nitrogen", percentage: 78.1, color: "hsl(210, 50%, 60%)" },
      { name: "Oxygen", percentage: 20.9, color: "hsl(200, 70%, 55%)" },
      { name: "Argon", percentage: 0.93, color: "hsl(270, 40%, 65%)" },
      { name: "CO₂", percentage: 0.04, color: "hsl(0, 0%, 55%)" },
    ],
    magneticField: { strength: "31.25 µT", type: "dipole", tilt: 11.5, description: "Strong dipole field generated by convection in the liquid iron outer core" },
  },
  mars: {
    geologicalFeatures: [
      { name: "Olympus Mons", type: "Shield Volcano", description: "Tallest volcano in the solar system at 21.9 km, 600 km base diameter" },
      { name: "Valles Marineris", type: "Canyon System", description: "4,000 km long canyon system, up to 7 km deep" },
      { name: "Hellas Planitia", type: "Impact Basin", description: "2,300 km wide, 7 km deep impact basin, largest visible crater" },
    ],
    atmosphere: [
      { name: "CO₂", percentage: 95.3, color: "hsl(0, 0%, 55%)" },
      { name: "Nitrogen", percentage: 2.7, color: "hsl(210, 50%, 60%)" },
      { name: "Argon", percentage: 1.6, color: "hsl(270, 40%, 65%)" },
      { name: "Oxygen", percentage: 0.13, color: "hsl(200, 70%, 55%)" },
    ],
    magneticField: { strength: "~0 µT", type: "crustal", tilt: 0, description: "No global field; localized crustal magnetic anomalies from ancient dynamo" },
  },
  jupiter: {
    geologicalFeatures: [
      { name: "Great Red Spot", type: "Storm", description: "Persistent anticyclonic storm, 1.3× Earth's diameter, >350 years old" },
      { name: "Equatorial Bands", type: "Atmospheric", description: "Alternating zones and belts of ammonia ice clouds driven by jet streams" },
      { name: "Galilean Moons", type: "Satellite System", description: "Io, Europa, Ganymede, Callisto — 4 large moons with diverse geology" },
    ],
    atmosphere: [
      { name: "Hydrogen", percentage: 89.8, color: "hsl(0, 0%, 75%)" },
      { name: "Helium", percentage: 10.2, color: "hsl(50, 80%, 70%)" },
    ],
    magneticField: { strength: "417 µT", type: "dipole", tilt: 9.6, description: "Strongest planetary magnetic field, 20,000× Earth's, generated by metallic hydrogen" },
  },
  saturn: {
    geologicalFeatures: [
      { name: "Ring System", type: "Rings", description: "Extensive ring system spanning 282,000 km, made of ice and rock particles" },
      { name: "Hexagonal Storm", type: "Storm", description: "Persistent hexagonal cloud pattern at the north pole, 30,000 km across" },
      { name: "Titan", type: "Moon", description: "Largest moon with thick nitrogen atmosphere and methane/ethane lakes" },
    ],
    atmosphere: [
      { name: "Hydrogen", percentage: 96.3, color: "hsl(0, 0%, 75%)" },
      { name: "Helium", percentage: 3.25, color: "hsl(50, 80%, 70%)" },
      { name: "Methane", percentage: 0.45, color: "hsl(160, 50%, 50%)" },
    ],
    magneticField: { strength: "21 µT", type: "dipole", tilt: 0.8, description: "Nearly perfectly aligned with rotation axis, generated by metallic hydrogen" },
  },
  uranus: {
    geologicalFeatures: [
      { name: "Tilted Axis", type: "Orbital", description: "97.77° axial tilt causes extreme seasonal variations, rolls on its side" },
      { name: "Ring System", type: "Rings", description: "13 known rings, dark and composed of small particles and dust" },
      { name: "Miranda", type: "Moon", description: "Most geologically diverse moon with 20 km deep canyons" },
    ],
    atmosphere: [
      { name: "Hydrogen", percentage: 82.5, color: "hsl(0, 0%, 75%)" },
      { name: "Helium", percentage: 15.2, color: "hsl(50, 80%, 70%)" },
      { name: "Methane", percentage: 2.3, color: "hsl(160, 50%, 50%)" },
    ],
    magneticField: { strength: "22.8 µT", type: "quadrupole", tilt: 58.6, description: "Highly tilted and offset from center, complex quadrupole-dominated field" },
  },
  neptune: {
    geologicalFeatures: [
      { name: "Great Dark Spot", type: "Storm", description: "Massive storm system similar to Jupiter's GRS, observed by Voyager 2 in 1989" },
      { name: "Supersonic Winds", type: "Atmospheric", description: "Fastest winds in the solar system at 2,100 km/h" },
      { name: "Triton", type: "Moon", description: "Retrograde orbit captured moon with active nitrogen geysers" },
    ],
    atmosphere: [
      { name: "Hydrogen", percentage: 80, color: "hsl(0, 0%, 75%)" },
      { name: "Helium", percentage: 19, color: "hsl(50, 80%, 70%)" },
      { name: "Methane", percentage: 1, color: "hsl(160, 50%, 50%)" },
    ],
    magneticField: { strength: "13.2 µT", type: "quadrupole", tilt: 46.9, description: "Highly tilted and offset, complex multipolar field similar to Uranus" },
  },
};
